;this file for FamiTone2 library generated by text2data tool

soundtrack_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; fEelings

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env5,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
@env2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c4,$c3,$c2,$c1,$c0,$00,$04
@env4:
	.byte $c2,$06,$c1,$00,$02
@env5:
	.byte $c0,$c0,$bf,$bd,$00,$03


; fEelings
@song0ch0:
	.byte $fb,$07
@song0ch0loop:
@ref0:
	.byte $82,$32,$85,$3f,$39,$3e,$85,$32,$85,$3f,$39,$34,$85,$32,$85,$39
	.byte $41,$44,$85,$45,$41,$41,$3b,$32,$85,$43,$41,$3f,$3b,$3d,$32,$89
	.byte $fd
	.word @song0ch0loop

; fEelings
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $84,$4a,$89,$51,$52,$85,$4a,$89,$51,$4c,$85,$4a,$89,$59,$5c,$85
	.byte $5c,$85,$58,$85,$4a,$85,$5a,$85,$57,$53,$4b,$52,$89
	.byte $fd
	.word @song0ch1loop

; fEelings
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; fEelings
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $88,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20,$8d,$20
	.byte $8d
	.byte $fd
	.word @song0ch3loop

; fEelings
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
