;this file for FamiTone2 library generated by text2data tool

soundtrack_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,204,170 ; Pomp and Circumstance - Haley Halcyon

@instruments:
	.byte $30 ;instrument $00
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env9,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env0,@env11
	.byte $00
	.byte $b0 ;instrument $07
	.word @env7,@env0,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env8,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0b
	.word @env8,@env10,@env0
	.byte $00
	.byte $b0 ;instrument $0c
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env6,@env0,@env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$a8,$0f	;1
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;25
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;27
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cc,$c9,$c6,$c3,$c0,$00,$05
@env2:
	.byte $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $c4,$c3,$c2,$c1,$c0,$00,$04
@env4:
	.byte $cf,$c9,$c6,$c4,$c2,$c1,$c0,$00,$06
@env5:
	.byte $cf,$03,$c0,$00,$02
@env6:
	.byte $cf,$05,$cf,$00,$02
@env7:
	.byte $c8,$cf,$cc,$c8,$c6,$c4,$c2,$c0,$00,$07
@env8:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5
	.byte $c4,$02,$c3,$02,$c2,$02,$c1,$03,$c0,$00,$18
@env9:
	.byte $c0,$c0,$bf,$bd,$00,$03
@env10:
	.byte $c0,$c0,$cc,$00,$02
@env11:
	.byte $e0,$f8,$ff,$ff,$ff,$00,$04


; Pomp and Circumstance - Haley Halcyon
@song0ch0:
	.byte $fb,$0c
@song0ch0loop:
@ref0:
	.byte $98,$37,$37,$37,$37,$31,$31,$31,$31,$3b,$3b,$37,$37,$3b,$3b,$37
	.byte $37,$29,$29,$2d,$2d,$27,$27,$27,$27,$31,$31,$2d,$2d,$29,$29,$27
	.byte $26,$81
@ref1:
	.byte $37,$37,$37,$37,$31,$31,$31,$31,$3b,$3b,$37,$37,$3b,$3b,$37,$37
	.byte $29,$29,$2d,$2d,$27,$27,$27,$27,$29,$29,$27,$27,$29,$41,$3f,$3c
	.byte $81
@ref2:
	.byte $33,$33,$37,$37,$31,$31,$31,$31,$3b,$3b,$37,$37,$31,$31,$31,$30
	.byte $81
	.byte $fd
	.word @song0ch0loop

; Pomp and Circumstance - Haley Halcyon
@song0ch1:
@song0ch1loop:
@ref3:
	.byte $98,$31,$31,$2d,$2d,$29,$29,$27,$27,$29,$29,$29,$29,$35,$35,$27
	.byte $27,$37,$37,$3b,$35,$37,$37,$31,$31,$3b,$3b,$35,$35,$33,$33,$33
	.byte $32,$81
@ref4:
	.byte $31,$31,$2d,$2d,$29,$29,$27,$27,$29,$29,$29,$29,$35,$35,$27,$27
	.byte $37,$37,$3b,$35,$37,$37,$2d,$2d,$3b,$3b,$37,$37,$37,$37,$37,$36
	.byte $81
@ref5:
	.byte $41,$41,$45,$3f,$41,$41,$3b,$3b,$45,$45,$3f,$3f,$37,$37,$37,$36
	.byte $81
	.byte $fd
	.word @song0ch1loop

; Pomp and Circumstance - Haley Halcyon
@song0ch2:
@song0ch2loop:
@ref6:
	.byte $86,$58,$85,$56,$58,$5d,$52,$85,$4e,$85,$4a,$85,$48,$4a,$4f,$44
	.byte $85,$00,$85,$48,$85,$4c,$4f,$52,$5c,$85,$4f,$01,$58,$83,$00,$58
	.byte $57,$52,$4e,$89,$00,$81
@ref7:
	.byte $58,$85,$56,$58,$5d,$52,$85,$4e,$85,$4a,$85,$48,$4a,$4f,$44,$85
	.byte $00,$85,$48,$85,$4c,$4f,$52,$5c,$85,$4f,$01,$62,$83,$00,$62,$61
	.byte $5c,$60,$89,$00,$81
@ref8:
	.byte $52,$85,$56,$59,$5c,$66,$85,$59,$01,$62,$83,$00,$62,$61,$5c,$58
	.byte $89,$00,$81
	.byte $fd
	.word @song0ch2loop

; Pomp and Circumstance - Haley Halcyon
@song0ch3:
@song0ch3loop:
@ref9:
	.byte $f9,$85
@ref10:
	.byte $f9,$85
@ref11:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

; Pomp and Circumstance - Haley Halcyon
@song0ch4:
@song0ch4loop:
@ref12:
	.byte $f9,$85
@ref13:
	.byte $f9,$85
@ref14:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
